"""
Static curriculum data for the Python track: the concept DAG, career
definitions, project suggestions, and tutor explanation content.
This is the single source of truth the frontend mirrors for layout only —
all mastery/state lives in the database.
"""

CONCEPTS = [
    {"id": "syntax_basics", "name": "Python Syntax & Variables", "level": 0, "diff": 1, "prereqs": [],
     "blurb": "Statements, variables, indentation, and print()."},
    {"id": "data_types", "name": "Data Types", "level": 1, "diff": 1, "prereqs": ["syntax_basics"],
     "blurb": "int, float, str, bool and how Python treats each."},
    {"id": "operators", "name": "Operators & Expressions", "level": 1, "diff": 1, "prereqs": ["syntax_basics"],
     "blurb": "Arithmetic, comparison, logical, assignment operators."},
    {"id": "control_flow", "name": "Control Flow", "level": 2, "diff": 2, "prereqs": ["operators"],
     "blurb": "if / elif / else branching and for / while loops."},
    {"id": "strings", "name": "String Manipulation", "level": 2, "diff": 2, "prereqs": ["data_types"],
     "blurb": "Slicing, formatting, and common string methods."},
    {"id": "lists_tuples", "name": "Lists & Tuples", "level": 2, "diff": 2, "prereqs": ["data_types"],
     "blurb": "Ordered collections — mutable lists vs immutable tuples."},
    {"id": "functions", "name": "Functions", "level": 3, "diff": 2, "prereqs": ["control_flow"],
     "blurb": "def, parameters, return values, and scope."},
    {"id": "dicts_sets", "name": "Dictionaries & Sets", "level": 3, "diff": 2, "prereqs": ["lists_tuples"],
     "blurb": "Key-value mappings and unique unordered collections."},
    {"id": "comprehensions", "name": "Comprehensions", "level": 4, "diff": 3, "prereqs": ["lists_tuples", "functions"],
     "blurb": "Concise list / dict / set construction in one expression."},
    {"id": "exceptions", "name": "Exception Handling", "level": 4, "diff": 3, "prereqs": ["functions"],
     "blurb": "try / except / finally and raising your own errors."},
    {"id": "modules_packages", "name": "Modules & Packages", "level": 4, "diff": 2, "prereqs": ["functions"],
     "blurb": "Organizing code with import, packages, __init__.py."},
    {"id": "oop_basics", "name": "OOP Basics", "level": 4, "diff": 3, "prereqs": ["functions", "dicts_sets"],
     "blurb": "Classes, objects, __init__, and self."},
    {"id": "file_handling", "name": "File Handling", "level": 5, "diff": 3, "prereqs": ["exceptions"],
     "blurb": "Reading and writing files safely with context managers."},
    {"id": "iterators_generators", "name": "Iterators & Generators", "level": 5, "diff": 4, "prereqs": ["comprehensions"],
     "blurb": "Lazy evaluation with yield and the iterator protocol."},
    {"id": "oop_advanced", "name": "Inheritance & Polymorphism", "level": 5, "diff": 4, "prereqs": ["oop_basics"],
     "blurb": "Subclassing, method overriding, multiple inheritance."},
    {"id": "data_structures_py", "name": "Data Structures in Python", "level": 5, "diff": 4, "prereqs": ["oop_basics", "lists_tuples"],
     "blurb": "Implementing stacks, queues, and trees from scratch."},
    {"id": "testing_py", "name": "Testing with pytest", "level": 5, "diff": 3, "prereqs": ["functions", "exceptions"],
     "blurb": "Writing asserts and tests that catch regressions."},
    {"id": "libraries_ecosystem", "name": "Libraries & Environments", "level": 5, "diff": 3, "prereqs": ["modules_packages"],
     "blurb": "pip, virtual environments, and third-party libraries."},
    {"id": "decorators", "name": "Decorators", "level": 6, "diff": 4, "prereqs": ["functions", "iterators_generators"],
     "blurb": "Wrapping functions to extend behaviour with @syntax."},
    {"id": "algorithms_py", "name": "Algorithms in Python", "level": 6, "diff": 4, "prereqs": ["data_structures_py", "control_flow"],
     "blurb": "Sorting, searching, and complexity analysis in practice."},
]
CONCEPT_MAP = {c["id"]: c for c in CONCEPTS}
MAX_LEVEL = max(c["level"] for c in CONCEPTS)

CAREERS = [
    {"id": "automation_engineer", "name": "Python Automation Engineer",
     "blurb": "Scripts and tools that eliminate repetitive manual work.",
     "weights": {"functions": 1, "file_handling": 1, "exceptions": 1, "modules_packages": 0.7,
                 "libraries_ecosystem": 1, "control_flow": 0.5}},
    {"id": "backend_developer", "name": "Python Backend Developer",
     "blurb": "Server-side logic, APIs, and application architecture.",
     "weights": {"functions": 1, "oop_basics": 1, "oop_advanced": 0.8, "exceptions": 0.7,
                 "modules_packages": 0.7, "testing_py": 0.8, "libraries_ecosystem": 0.6}},
    {"id": "data_analyst", "name": "Python Data Analyst",
     "blurb": "Turning raw data into insight with Python's data tooling.",
     "weights": {"data_types": 0.6, "lists_tuples": 0.8, "dicts_sets": 0.8, "comprehensions": 0.7,
                 "strings": 0.6, "libraries_ecosystem": 1}},
    {"id": "software_engineer", "name": "Python Software Engineer — DSA Track",
     "blurb": "Strong fundamentals in data structures and algorithms.",
     "weights": {"control_flow": 0.6, "functions": 0.8, "data_structures_py": 1, "algorithms_py": 1,
                 "oop_basics": 0.7, "oop_advanced": 0.6}},
    {"id": "qa_engineer", "name": "Python QA / Test Automation Engineer",
     "blurb": "Building automated test suites and quality pipelines.",
     "weights": {"functions": 0.8, "exceptions": 0.8, "testing_py": 1, "file_handling": 0.6,
                 "modules_packages": 0.5, "libraries_ecosystem": 0.7}},
]
CAREER_MAP = {c["id"]: c for c in CAREERS}

PROJECTS = [
    {"id": "contact_cli", "title": "Contact Book CLI", "concepts": ["oop_basics", "file_handling", "dicts_sets"],
     "blurb": "A command-line contact manager that saves and loads entries from a file.", "tech": ["Python", "JSON"]},
    {"id": "word_freq", "title": "Word Frequency Analyzer", "concepts": ["dicts_sets", "strings", "lists_tuples"],
     "blurb": "Parse a text file and rank its most common words.", "tech": ["Python", "collections"]},
    {"id": "weather_cli", "title": "Weather Lookup CLI", "concepts": ["libraries_ecosystem", "exceptions", "functions"],
     "blurb": "Fetch live weather for a city from a public API.", "tech": ["Python", "requests"]},
    {"id": "ds_library", "title": "Custom Data Structure Library", "concepts": ["data_structures_py", "algorithms_py", "oop_advanced"],
     "blurb": "Implement your own stack, queue and BST, each with tests.", "tech": ["Python", "pytest"]},
    {"id": "calc_tests", "title": "Tested Calculator Module", "concepts": ["testing_py", "functions", "exceptions"],
     "blurb": "Build a calculator module with a full pytest suite covering edge cases.", "tech": ["Python", "pytest"]},
]

TUTOR_CONTENT = {
    "syntax_basics": {"beg": "Python reads top to bottom. Indentation (not braces) defines blocks, so consistent spacing isn't a style choice — it's syntax.",
                       "adv": "Indentation is enforced by the tokenizer via INDENT/DEDENT tokens, which is why mixing tabs and spaces raises a TabError.",
                       "ex": "name = \"Ada\"\nprint(f\"Hello, {name}\")"},
    "data_types": {"beg": "Every value has a type — int, float, str, bool — and Python figures it out automatically, no declarations needed.",
                   "adv": "Python is dynamically but strongly typed: variables are just names bound to objects, and implicit coercion is intentionally limited.",
                   "ex": "x = 7          # int\ny = 3.5        # float\nname = \"Rex\"   # str"},
    "operators": {"beg": "Operators combine values: + - * / for math, == != < > for comparisons, and and/or/not for logic.",
                  "adv": "Comparison operators can be chained (1 < x < 10), and + is resolved via dunder methods (__add__) on the operands.",
                  "ex": "print(10 % 3)   # 1\nprint(2 ** 10)  # 1024"},
    "control_flow": {"beg": "if/elif/else picks a branch to run, and for/while loops repeat code while a condition holds.",
                      "adv": "for loops iterate over any iterable via the iterator protocol; while loops pair well with sentinel or state-machine style conditions.",
                      "ex": "for i in range(3):\n    if i == 1:\n        print(\"one\")"},
    "strings": {"beg": "Strings are sequences of characters — slice them with [start:end], and use f-strings to build new ones.",
                "adv": "Strings are immutable; every 'modification' method returns a new object, which matters for performance in tight loops.",
                "ex": "s = \"python\"\nprint(s[:3], s.upper())"},
    "lists_tuples": {"beg": "Lists are ordered and changeable ([1,2,3]); tuples are ordered but frozen once created ((1,2,3)).",
                      "adv": "Tuples' immutability makes them hashable when their contents are hashable, so they can be dict keys — lists never can.",
                      "ex": "nums = [3, 1, 2]\nnums.sort()\npoint = (10, 20)"},
    "functions": {"beg": "def name(params): defines reusable code. Arguments come in, a value optionally comes out via return.",
                  "adv": "Python supports default args, *args/**kwargs, and closures — functions are first-class objects you can pass around.",
                  "ex": "def add(a, b=0):\n    return a + b"},
    "dicts_sets": {"beg": "Dicts store key → value pairs; sets store unique values with no order guarantee (conceptually).",
                   "adv": "Both are hash-table backed, giving average O(1) lookup — but keys/set members must be hashable.",
                   "ex": "ages = {\"Ada\": 30}\nunique = {1, 2, 2, 3}"},
    "comprehensions": {"beg": "A comprehension builds a collection in one line: [expr for item in iterable if condition].",
                        "adv": "Comprehensions create their own scope in Python 3 and are typically faster than an equivalent for-loop + append.",
                        "ex": "evens = [x for x in range(10) if x % 2 == 0]"},
    "exceptions": {"beg": "Wrap risky code in try:, catch problems in except:, and finally: always runs to clean up.",
                   "adv": "Prefer catching specific exception types over bare except:, and use custom exception classes to carry structured error context.",
                   "ex": "try:\n    1 / 0\nexcept ZeroDivisionError as e:\n    print(e)"},
    "modules_packages": {"beg": "import brings code from another file into yours. A folder of modules becomes a package.",
                          "adv": "Python resolves imports via sys.path; relative imports (from . import x) only work correctly inside a real package.",
                          "ex": "import math\nfrom math import sqrt"},
    "oop_basics": {"beg": "A class is a blueprint; objects are instances of it. self refers to 'this particular object'.",
                   "adv": "__init__ is the initializer (not a constructor — __new__ is), and attributes live in the instance's __dict__ by default.",
                   "ex": "class Dog:\n    def __init__(self, name):\n        self.name = name"},
    "file_handling": {"beg": "Use with open(path) as f: to read or write files — it closes the file automatically, even on errors.",
                       "adv": "Always specify encoding explicitly (encoding='utf-8') to avoid platform-dependent default-encoding bugs.",
                       "ex": "with open(\"notes.txt\") as f:\n    text = f.read()"},
    "iterators_generators": {"beg": "A generator uses yield to produce values one at a time, instead of building a whole list in memory.",
                              "adv": "Generators implement the iterator protocol lazily; ideal for streaming large or infinite sequences with constant memory.",
                              "ex": "def countdown(n):\n    while n > 0:\n        yield n\n        n -= 1"},
    "oop_advanced": {"beg": "A subclass inherits from a parent class and can override its methods to specialize behaviour.",
                      "adv": "Python's MRO (C3 linearization) determines method lookup order under multiple inheritance — check it with Cls.__mro__.",
                      "ex": "class Animal:\n    def speak(self): return \"...\"\nclass Dog(Animal):\n    def speak(self): return \"Woof\""},
    "data_structures_py": {"beg": "You can build a stack or queue with a plain list, and a tree with linked node objects that reference children.",
                            "adv": "collections.deque gives O(1) appends/pops from both ends, making it a better queue than list.pop(0) which is O(n).",
                            "ex": "from collections import deque\nq = deque()\nq.append(1); q.popleft()"},
    "testing_py": {"beg": "pytest lets you write plain functions with assert statements — pytest finds and runs them automatically.",
                    "adv": "Use fixtures for setup/teardown and parametrize to run one test against many inputs without duplicating code.",
                    "ex": "def test_add():\n    assert 2 + 2 == 4"},
    "libraries_ecosystem": {"beg": "pip install <package> adds third-party code; a virtual environment keeps each project's packages separate.",
                             "adv": "Pin exact versions in requirements.txt (or a lockfile) so environments are reproducible across machines.",
                             "ex": "python -m venv .venv\npip install requests"},
    "decorators": {"beg": "A decorator wraps a function to add behaviour, using @decorator syntax right above the def.",
                    "adv": "Well-written decorators use functools.wraps to preserve the wrapped function's __name__ and docstring for introspection.",
                    "ex": "def logged(fn):\n    def wrapper(*a, **k):\n        print(\"calling\", fn.__name__)\n        return fn(*a, **k)\n    return wrapper"},
    "algorithms_py": {"beg": "Sorting and searching are the classics — know at least one O(n log n) sort and binary search cold.",
                       "adv": "Reason about complexity in terms of input growth; Python's sorted() is Timsort — O(n log n) worst case and stable.",
                       "ex": "def binary_search(arr, target):\n    lo, hi = 0, len(arr) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if arr[mid] == target: return mid\n        if arr[mid] < target: lo = mid + 1\n        else: hi = mid - 1\n    return -1"},
}
