QUESTIONS = [
    {"id": "q1", "concept_id": "syntax_basics", "diff": 1, "q": "Which symbol starts a single-line comment in Python?",
     "opts": ["//", "#", "<!--", "/*"], "correct": 1, "exp": "Python uses # for single-line comments."},
    {"id": "q2", "concept_id": "syntax_basics", "diff": 1, "q": "What does print(type(5)) output?",
     "opts": ["<class 'int'>", "<class 'float'>", "<class 'str'>", "<class 'number'>"], "correct": 0,
     "exp": "5 is a plain integer literal, so type(5) is int."},
    {"id": "q3", "concept_id": "data_types", "diff": 1, "q": "Which of these is an immutable data type?",
     "opts": ["list", "dict", "tuple", "set"], "correct": 2, "exp": "Tuples cannot be modified after creation."},
    {"id": "q4", "concept_id": "data_types", "diff": 1, "q": "What is the type of the value True?",
     "opts": ["int", "bool", "str", "float"], "correct": 1, "exp": "True/False are of type bool (a subclass of int)."},
    {"id": "q5", "concept_id": "operators", "diff": 1, "q": "What does the // operator do?",
     "opts": ["Float division", "Floor division", "Modulus", "Exponent"], "correct": 1, "exp": "// performs floor (integer) division."},
    {"id": "q6", "concept_id": "operators", "diff": 1, "q": "What is 3 ** 2?",
     "opts": ["6", "9", "5", "1"], "correct": 1, "exp": "** is exponentiation, so 3**2 = 9."},
    {"id": "q7", "concept_id": "control_flow", "diff": 2, "q": "Which line starts an intentional infinite loop?",
     "opts": ["while True:", "loop:", "repeat:", "for ever:"], "correct": 0, "exp": "while True: loops until an explicit break."},
    {"id": "q8", "concept_id": "control_flow", "diff": 2, "q": "What does 'continue' do inside a loop?",
     "opts": ["Exits the loop", "Skips to the next iteration", "Pauses execution", "Restarts the program"], "correct": 1,
     "exp": "continue skips the rest of the current iteration."},
    {"id": "q9", "concept_id": "strings", "diff": 2, "q": 'What does "Hello"[1:4] return?',
     "opts": ["Hell", "ell", "ello", "Hel"], "correct": 1, "exp": "Slicing [1:4] takes indices 1,2,3 → 'ell'."},
    {"id": "q10", "concept_id": "strings", "diff": 2, "q": "Which method converts a string to uppercase?",
     "opts": [".upper()", ".toUpper()", ".capitalize()", ".upperCase()"], "correct": 0, "exp": "Strings expose .upper() for uppercasing."},
    {"id": "q11", "concept_id": "lists_tuples", "diff": 2, "q": "Which literal creates an empty tuple?",
     "opts": ["[]", "{}", "()", "(,)"], "correct": 2, "exp": "() is an empty tuple; {} is an empty dict."},
    {"id": "q12", "concept_id": "lists_tuples", "diff": 2, "q": "What does list.append(x) do?",
     "opts": ["Inserts x at the start", "Removes x", "Adds x to the end", "Sorts the list"], "correct": 2,
     "exp": "append() adds a single element to the end of the list."},
    {"id": "q13", "concept_id": "functions", "diff": 2, "q": "What keyword defines a function?",
     "opts": ["func", "def", "function", "lambda"], "correct": 1, "exp": "def introduces a function definition."},
    {"id": "q14", "concept_id": "functions", "diff": 2, "q": "What does a function return if it has no return statement?",
     "opts": ["0", "None", "An error", "Empty string"], "correct": 1, "exp": "Functions implicitly return None."},
    {"id": "q15", "concept_id": "dicts_sets", "diff": 2, "q": "How do you access value for key k in dict d?",
     "opts": ["d.k", "d[k]", "d(k)", "d->k"], "correct": 1, "exp": "Square-bracket indexing looks up a key in a dict."},
    {"id": "q16", "concept_id": "dicts_sets", "diff": 2, "q": "Which structure holds unique, unordered elements?",
     "opts": ["list", "tuple", "set", "string"], "correct": 2, "exp": "A set automatically discards duplicates."},
    {"id": "q17", "concept_id": "comprehensions", "diff": 3, "q": "What does [x*2 for x in range(3)] evaluate to?",
     "opts": ["[0,2,4]", "[0,1,2]", "[2,4,6]", "[1,2,3]"], "correct": 0, "exp": "range(3) → 0,1,2, doubled → 0,2,4."},
    {"id": "q18", "concept_id": "comprehensions", "diff": 3, "q": "List comprehensions are mainly used to:",
     "opts": ["Define classes", "Build lists concisely", "Handle exceptions", "Open files"], "correct": 1,
     "exp": "They're a compact syntax for building lists."},
    {"id": "q19", "concept_id": "exceptions", "diff": 3, "q": "Which block always executes, error or not?",
     "opts": ["try", "except", "finally", "raise"], "correct": 2, "exp": "finally runs regardless of whether an exception occurred."},
    {"id": "q20", "concept_id": "exceptions", "diff": 3, "q": "Which keyword manually raises an exception?",
     "opts": ["throw", "raise", "error", "except"], "correct": 1, "exp": "Python uses raise, not throw."},
    {"id": "q21", "concept_id": "modules_packages", "diff": 2, "q": "Which statement imports the math module?",
     "opts": ["#include math", "import math", "using math", "require('math')"], "correct": 1, "exp": "import math is the standard form."},
    {"id": "q22", "concept_id": "modules_packages", "diff": 2, "q": "A directory becomes a package (classic style) if it contains a:",
     "opts": ["main.py", "__init__.py", "package.json", "setup.cfg"], "correct": 1, "exp": "__init__.py historically marks a package."},
    {"id": "q23", "concept_id": "oop_basics", "diff": 3, "q": "What keyword defines a class?",
     "opts": ["class", "struct", "object", "def"], "correct": 0, "exp": "class starts a class definition."},
    {"id": "q24", "concept_id": "oop_basics", "diff": 3, "q": "What does 'self' refer to in a method?",
     "opts": ["The class itself", "The current instance", "Nothing, it's unused", "The parent module"], "correct": 1,
     "exp": "self is the conventional name for the instance."},
    {"id": "q25", "concept_id": "file_handling", "diff": 3, "q": "Which mode opens a file for appending?",
     "opts": ["'r'", "'w'", "'a'", "'x'"], "correct": 2, "exp": "'a' opens for append, writing past existing content."},
    {"id": "q26", "concept_id": "file_handling", "diff": 3, "q": "What's the recommended way to open a file so it auto-closes?",
     "opts": ["open() alone", "with open() as f:", "file.open()", "try/open"], "correct": 1,
     "exp": "The with statement closes the file automatically."},
    {"id": "q27", "concept_id": "iterators_generators", "diff": 4, "q": "Which keyword creates a generator function?",
     "opts": ["return", "yield", "gen", "iter"], "correct": 1, "exp": "yield turns a function into a generator."},
    {"id": "q28", "concept_id": "iterators_generators", "diff": 4, "q": "Which method must an iterator implement to produce values?",
     "opts": ["__next__", "__iter__ only", "__gen__", "__loop__"], "correct": 0,
     "exp": "__next__ returns the next value or raises StopIteration."},
    {"id": "q29", "concept_id": "oop_advanced", "diff": 4, "q": "Providing a new implementation of a parent's method is called:",
     "opts": ["Encapsulation", "Overriding", "Overloading", "Abstraction"], "correct": 1,
     "exp": "Method overriding replaces the inherited behaviour."},
    {"id": "q30", "concept_id": "oop_advanced", "diff": 4, "q": "Python supports multiple inheritance by:",
     "opts": ["Not at all", "Listing multiple base classes", "Interfaces only", "Mixins exclusively"], "correct": 1,
     "exp": "class C(A, B): lists multiple bases directly."},
    {"id": "q31", "concept_id": "data_structures_py", "diff": 4, "q": "Which structure is LIFO (Last In, First Out)?",
     "opts": ["Queue", "Stack", "Tree", "Graph"], "correct": 1, "exp": "A stack pops the most recently pushed item first."},
    {"id": "q32", "concept_id": "data_structures_py", "diff": 4, "q": "A Python list can directly serve as a:",
     "opts": ["Only a queue", "Only a stack", "Stack or queue (with trade-offs)", "Neither"], "correct": 2,
     "exp": "Lists support both, though deque is more efficient for queues."},
    {"id": "q33", "concept_id": "testing_py", "diff": 3, "q": "Which library is most commonly used for writing tests in Python?",
     "opts": ["pytest", "numpy", "flask", "requests"], "correct": 0, "exp": "pytest is the de-facto standard testing framework."},
    {"id": "q34", "concept_id": "testing_py", "diff": 3, "q": "What is the purpose of an assert statement in a test?",
     "opts": ["Print output", "Verify a condition is true", "Import a module", "Handle exceptions"], "correct": 1,
     "exp": "assert fails the test if the condition is false."},
    {"id": "q35", "concept_id": "libraries_ecosystem", "diff": 3, "q": "Which command installs a third-party package?",
     "opts": ["python install pkg", "pip install pkg", "get pkg", "import pkg"], "correct": 1, "exp": "pip is Python's package installer."},
    {"id": "q36", "concept_id": "libraries_ecosystem", "diff": 3, "q": "What is a virtual environment used for?",
     "opts": ["Running Python faster", "Isolating project dependencies", "Compiling code", "Debugging syntax"], "correct": 1,
     "exp": "venvs keep each project's dependencies separate."},
    {"id": "q37", "concept_id": "decorators", "diff": 4, "q": "What symbol applies a decorator to a function?",
     "opts": ["#", "@", "&", "::"], "correct": 1, "exp": "@decorator_name goes just above the function definition."},
    {"id": "q38", "concept_id": "decorators", "diff": 4, "q": "A decorator is essentially a function that:",
     "opts": ["Deletes another function", "Wraps and extends another function", "Only works on classes", "Replaces Python syntax"], "correct": 1,
     "exp": "Decorators take a function and return an enhanced version."},
    {"id": "q39", "concept_id": "algorithms_py", "diff": 4, "q": "What is the average time complexity of binary search?",
     "opts": ["O(n)", "O(log n)", "O(n^2)", "O(1)"], "correct": 1, "exp": "Binary search halves the search space each step."},
    {"id": "q40", "concept_id": "algorithms_py", "diff": 4, "q": "Which sort repeatedly swaps adjacent out-of-order elements?",
     "opts": ["Merge sort", "Bubble sort", "Quick sort", "Binary search"], "correct": 1, "exp": "Bubble sort's defining move is adjacent swaps."},
]
